name: Test
on: [ push, pull_request ]
jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm install -g c8 jshint uglify-js
    - run: npm install
    - run: npm test
    - uses: coverallsapp/github-action@master
      name: Upload to coveralls.io
      with:
        github-token: ${{ github.token }}
  CodeQL:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: github/codeql-action/init@v2
      with:
        languages: javascript
    - uses: github/codeql-action/analyze@v2
      name: Perform CodeQL Analysis
      with:
        category: '/language:javascript'

